### ISSUE TITLE
Released decoder module cannot be recreated.

### ISSUE THREAD

**Issue by donmccurdy** [google/draco#349]
Working on implementing KHR_draco_mesh_compression in [my viewer](https://gltf-viewer.donmccurdy.com/), and ran into this issue: I'd like to release allocated memory after loading a model, so I call `THREE.DRACOLoader.releaseDecoderModule();`.  Having done that, future attempts to use THREE.DRACOLoader will fail:

```
draco_wasm_wrapper.js:83 Uncaught (in promise) TypeError: Cannot read property 'apply' of undefined
    at DracoDecoderModule.a._emscripten_enum_draco_StatusCode_OK (draco_wasm_wrapper.js:83)
    at b (draco_wasm_wrapper.js:114)
    at draco_wasm_wrapper.js:114
    at DracoDecoderModule (draco_wasm_wrapper.js:114)
    at bundle.js?v=r90:445
    at new Promise (<anonymous>)
    at bundle.js?v=r90:439
    at <anonymous>
```

Live demo: https://three-gltf-viewer-qgknamimbz.now.sh/

Here is the [diff for how I'm using DRACOLoader](https://github.com/donmccurdy/three-gltf-viewer/compare/feat-draco).

**Comment by FrankGalligan** [comment]
@donmccurdy I think this is fixed correct?

**Comment by donmccurdy** [comment]
I can still reproduce this issue with the latest decoder on the [glTF 2.0 branch](https://github.com/google/draco/tree/gltf_2.0_draco_extension/javascript). Once `releaseDecoderModule()` has been invoked, the decoder cannot be recreated.

**Comment by FrankGalligan** [comment]
Is this still an issue?

**Comment by donmccurdy** [comment]
I'm no longer able to test this, as the three.js Draco implementation now runs in a Web Worker and can only be re-initialized by creating a new Web Worker. So, unfortunately, I'm not sure!
