### ISSUE TITLE
draco_decoder.js Issue with bigger drc files

### ISSUE THREAD

**Issue by trox667** [google/draco#82]
Hi,
first of all, thanks for this framework, the results are awesome.

I have encoded several OBJ files to DRC and sucessfully decoded them back to OBJ using the provided tools. It works fine for all different sizes of OBJ files.

But using the provided THREE.js sample (webgl_loader_draco.html), I am not able to decode bigger DRC files. I tried to load files which are bigger than 16MB (~7million points, normals and colors) and got the following error: THREE.DRACOLoader: Unknown geometry type.
DRACOLoader.js Line 80

Using the CPP draco_decoder, i was able to decode these bigger files to OBJ and load it using an OBJ viewer. So the file itself looks fine. 

I tried several smaller DRC files ~5MB which are working fine. I don't have any other files to figure out a possible memory limit. 

My System: macOS 10.12.3 - Google Chrome Version 57.0.2987.110 (64-bit)
I also tested it on a Windows 10 machine with Chrome and Firefox with the same error message.

Is there any known memory limit? 
Thank you in advance for any hints/ideas.

**Comment by ondys** [comment]
Thanks for the report. I've been able to reproduce the issue and I'm investigating it.

**Comment by ondys** [comment]
We have a fix for the issue internally and we will post an external update with a new .js decoder early next week.

**Comment by ondys** [comment]
@trox667 We just pushed new javascript decoders to the master branch that should work with larger meshes. Please give it a try and let us know if it solved your problems. Thanks!

**Comment by trox667** [comment]
Hi, 
thanks for the quick fix. I tried several models above 16MB and everything is working fine now.
Thanks a lot!

**Comment by YouYue123** [comment]
I am still facing this issue in version 1.3.5. Is this a regression bug?
